---
- name: Install banana
  hosts: bananas
  pre_tasks:
    - name: "Create User"
      sudo: yes
      user:
        name=banana
        home=/home/banana
        system=yes
        shell=/bin/bash
      tags: banana

  roles:
    - role: "nvm"
      nvm:
        user: "banana"
        version: "HEAD"
        node_version: "0.10.35"

    - role: "banana"
