---

- name: Install banana
  sudo: yes
  sudo_user: "{{ banana.user }}"
  git:
    repo=https://github.com/supertylerc/banana.git
    dest=~/banana
  tags: banana

- name: Copy banana Configuration
  sudo: yes
  sudo_user: "{{ banana.user }}"
  copy:
    src=config.yml
    dest=~/banana/config/config.yml
    group=banana
    owner=banana
    mode=0400
  tags: banana

- name: Install coffeescript
  sudo: yes
  sudo_user: "{{ banana.user }}"
  npm:
    name=coffee-script
    path=/home/{{ banana.user }}/.nvm/v{{ banana.node_version }}/lib/node_modules
    executable=/home/{{ banana.user }}/.nvm/v{{ banana.node_version }}/bin/npm
  tags: banana

- name: Install Dependencies
  sudo: yes
  sudo_user: "{{ banana.user }}"
  npm:
    path=/home/{{ banana.user }}/banana
    executable=/home/{{ banana.user }}/.nvm/v{{ banana.node_version }}/bin/npm
  tags: banana

- name: Compile banana
  sudo: yes
  #sudo_user: "{{ banana.user }}"
  command:
    sudo -iu {{ banana.user }} /home/{{ banana.user }}/.nvm/v{{ banana.node_version }}/lib/node_modules/coffee-script/bin/coffee -c --output banana banana
    chdir=/home/{{ banana.user }}/banana
  tags: banana
