---

- name: Install Dependencies
  sudo: yes
  apt:
    pkg={{ item }}
    update_cache=yes
    cache_valid_time=3600
  with_items: [ git, curl, build-essential, libssl-dev ]
  tags: [ nvm, banana ]

