---

- include: apt.yml
  when: ansible_pkg_mgr == 'apt'
- include: yum.yml
  when: ansible_pkg_mgr == 'yum'

- name: Install nvm
  sudo: yes
  sudo_user: "{{ nvm.user }}"
  git:
    repo=https://github.com/creationix/nvm.git
    dest=~/.nvm
    version={{ nvm.version }}
  tags: nvm

- name: Source nvm
  sudo: yes
  sudo_user: "{{ nvm.user }}"
  lineinfile:
    dest=~/.profile
    line="source ~/.nvm/nvm.sh"
  tags: nvm

- name: Install node.js {{ nvm.node_version }}
  command: sudo -iu {{ nvm.user }} nvm install {{ nvm.node_version }}
  register: node_install
  changed_when: "'is already installed.' not in node_install.stdout"
  tags: [ nvm, nodejs ]

- name: Check Default node.js Version ({{ nvm.node_version }})
  shell:
    sudo -iu {{ nvm.user }} nvm ls | grep -e 'default -> {{ nvm.node_version }}'
  register: nvm_version_check
  changed_when: False
  ignore_errors: True
  tags: [ nvm, nodejs ]

- name: Set Default Node Version to {{ nvm.node_version }}
  command: sudo -iu {{ nvm.user }} nvm alias default {{ nvm.node_version }}
  when: node_version_check|failed
  tags: [ nvm, node ]

- name: 
